"""Add verification fields

Revision ID: 29ecd925f9dd
Revises: 7237c3b84921
Create Date: 2026-07-11 23:13:00.558630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ecd925f9dd'
down_revision: Union[str, Sequence[str], None] = '7237c3b84921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum', sa.String(), nullable=True))

    with op.batch_alter_table('restore_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test_restore', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restore_jobs', schema=None) as batch_op:
        batch_op.drop_column('is_test_restore')

    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.drop_column('checksum')

    # ### end Alembic commands ###
