"""Add StorageTarget and Encryption

Revision ID: 3f623b7e73da
Revises: 293deac14745
Create Date: 2026-07-12 00:07:30.403088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f623b7e73da'
down_revision: Union[str, Sequence[str], None] = '293deac14745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('smb_unc_path', sa.String(), nullable=True),
    sa.Column('smb_user', sa.String(), nullable=True),
    sa.Column('smb_password', sa.String(), nullable=True),
    sa.Column('nfs_path', sa.String(), nullable=True),
    sa.Column('s3_endpoint', sa.String(), nullable=True),
    sa.Column('s3_access_key', sa.String(), nullable=True),
    sa.Column('s3_secret_key', sa.String(), nullable=True),
    sa.Column('s3_bucket', sa.String(), nullable=True),
    sa.Column('s3_region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_targets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_targets_name'), ['name'], unique=True)

    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_target_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vms_storage_target_id_storage_targets', 'storage_targets', ['storage_target_id'], ['id'])

    # Manual Data Migration: copy storage config from config to storage_targets
    connection = op.get_bind()
    config_rows = connection.execute(sa.text("SELECT id, storage_type, smb_unc_path, smb_user, smb_password, nfs_path, s3_endpoint, s3_access_key, s3_secret_key, s3_bucket, s3_region FROM config")).fetchall()
    
    if config_rows:
        row = config_rows[0]
        # Only create a target if there is some path/endpoint defined
        if row.smb_unc_path or row.nfs_path or row.s3_endpoint or row.s3_bucket:
            connection.execute(sa.text("""
                INSERT INTO storage_targets (
                    name, is_default, storage_type, smb_unc_path, smb_user, smb_password, 
                    nfs_path, s3_endpoint, s3_access_key, s3_secret_key, s3_bucket, s3_region
                ) VALUES (
                    'Default Storage', 1, :storage_type, :smb_unc_path, :smb_user, :smb_password, 
                    :nfs_path, :s3_endpoint, :s3_access_key, :s3_secret_key, :s3_bucket, :s3_region
                )
            """), {
                "storage_type": row.storage_type or "SMB",
                "smb_unc_path": row.smb_unc_path,
                "smb_user": row.smb_user,
                "smb_password": row.smb_password,
                "nfs_path": row.nfs_path,
                "s3_endpoint": row.s3_endpoint,
                "s3_access_key": row.s3_access_key,
                "s3_secret_key": row.s3_secret_key,
                "s3_bucket": row.s3_bucket,
                "s3_region": row.s3_region
            })
            
            # Get the newly inserted target ID
            target_id_row = connection.execute(sa.text("SELECT id FROM storage_targets WHERE name='Default Storage'")).fetchone()
            if target_id_row:
                target_id = target_id_row.id
                # Update all VMs to point to the new default storage target
                connection.execute(sa.text(f"UPDATE vms SET storage_target_id={target_id}"))

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.String(), nullable=True))
        batch_op.drop_column('s3_endpoint')
        batch_op.drop_column('s3_secret_key')
        batch_op.drop_column('s3_region')
        batch_op.drop_column('smb_unc_path')
        batch_op.drop_column('smb_user')
        batch_op.drop_column('storage_type')
        batch_op.drop_column('smb_password')
        batch_op.drop_column('s3_bucket')
        batch_op.drop_column('nfs_path')
        batch_op.drop_column('s3_access_key')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('storage_target_id')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_access_key', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('nfs_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('s3_bucket', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('smb_password', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('storage_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('smb_user', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('smb_unc_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('s3_region', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('s3_secret_key', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('s3_endpoint', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('encryption_key')

    with op.batch_alter_table('storage_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_targets_name'))
        batch_op.drop_index(batch_op.f('ix_storage_targets_id'))

    op.drop_table('storage_targets')
    # ### end Alembic commands ###
