"""Add vCenter CBT fields

Revision ID: 5bb0f6044760
Revises: 2cc502995896
Create Date: 2026-07-11 22:58:38.397831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb0f6044760'
down_revision: Union[str, Sequence[str], None] = '2cc502995896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_incremental', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parent_backup_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_backup_logs_parent_backup_id', 'backup_logs', ['parent_backup_id'], ['id'])

    with op.batch_alter_table('esxi_hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esxi_hosts', schema=None) as batch_op:
        batch_op.drop_column('host_type')

    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_backup_id')
        batch_op.drop_column('is_incremental')
        batch_op.drop_column('change_id')

    # ### end Alembic commands ###
