"""Add webhook fields

Revision ID: 7237c3b84921
Revises: 5bb0f6044760
Create Date: 2026-07-11 23:06:45.182124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7237c3b84921'
down_revision: Union[str, Sequence[str], None] = '5bb0f6044760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('daily_report_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('daily_report_time')
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
