"""Initial schema

Revision ID: ce76489cc0e1
Revises: 
Create Date: 2026-07-11 21:37:02.505981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce76489cc0e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_username'), ['username'], unique=False)

    op.create_table('backup_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_logs_id'), ['id'], unique=False)

    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smb_unc_path', sa.String(), nullable=True),
    sa.Column('smb_user', sa.String(), nullable=True),
    sa.Column('smb_password', sa.String(), nullable=True),
    sa.Column('smtp_server', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.String(), nullable=True),
    sa.Column('smtp_to_email', sa.String(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('imap_server', sa.String(), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('imap_user', sa.String(), nullable=True),
    sa.Column('imap_password', sa.String(), nullable=True),
    sa.Column('imap_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('perf_parallel_threads', sa.Integer(), nullable=True),
    sa.Column('perf_compression_level', sa.Integer(), nullable=True),
    sa.Column('backup_timeout_mins', sa.Integer(), nullable=True),
    sa.Column('max_global_backups', sa.Integer(), nullable=True),
    sa.Column('max_backups_per_host', sa.Integer(), nullable=True),
    sa.Column('datastore_min_free_pct', sa.Integer(), nullable=True),
    sa.Column('datastore_headroom_gb', sa.Integer(), nullable=True),
    sa.Column('datastore_est_multiplier', sa.Float(), nullable=True),
    sa.Column('scheduler_paused', sa.Boolean(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('nfs_path', sa.String(), nullable=True),
    sa.Column('s3_endpoint', sa.String(), nullable=True),
    sa.Column('s3_access_key', sa.String(), nullable=True),
    sa.Column('s3_secret_key', sa.String(), nullable=True),
    sa.Column('s3_bucket', sa.String(), nullable=True),
    sa.Column('s3_region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_id'), ['id'], unique=False)

    op.create_table('esxi_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('host_ip', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('esxi_hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esxi_hosts_id'), ['id'], unique=False)

    op.create_table('restore_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.Column('target_esxi_host', sa.String(), nullable=True),
    sa.Column('datastore', sa.String(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_action', sa.String(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restore_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restore_jobs_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notify_subscriptions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('vms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esxi_host_id', sa.Integer(), nullable=True),
    sa.Column('vm_name', sa.String(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('storage_gb', sa.Float(), nullable=True),
    sa.Column('schedule_hour', sa.Integer(), nullable=True),
    sa.Column('schedule_minute', sa.Integer(), nullable=True),
    sa.Column('retention_count', sa.Integer(), nullable=True),
    sa.Column('is_job_active', sa.Boolean(), nullable=True),
    sa.Column('schedule_frequency', sa.String(), nullable=True),
    sa.Column('schedule_days', sa.String(), nullable=True),
    sa.Column('last_backup', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_action', sa.String(), nullable=True),
    sa.Column('power_state', sa.String(), nullable=True),
    sa.Column('speed_mbps', sa.Float(), nullable=True),
    sa.Column('power_off_for_backup', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['esxi_host_id'], ['esxi_hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vm_name')
    )
    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vms_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vms_id'))

    op.drop_table('vms')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('restore_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restore_jobs_id'))

    op.drop_table('restore_jobs')
    with op.batch_alter_table('esxi_hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esxi_hosts_id'))

    op.drop_table('esxi_hosts')
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_id'))

    op.drop_table('config')
    with op.batch_alter_table('backup_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_logs_id'))

    op.drop_table('backup_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
